name: Java CI with Gradle

on:
  push:
    branches: [ master, main ]
    tags: [ "**" ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: |
        ./gradlew build
    - name: Rename bot jar
      run: |
        ls
        mv OSRSBot*.jar ./OsrsBot.jar
    - uses: actions/upload-artifact@v2
      with:
        name: OsrsBot.jar
        path: ./OsrsBot.jar
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./OsrsBot.jar

